---
- name: Install Local Repo
  template: src=repo.j2 dest=/etc/yum.repos.d/local.repo

- name: Install Java 1.7 and some basic dependencies
  shell: yum install -y {{ item }} --disablerepo='*' --enablerepo='local'
  with_items:
   - unzip
   - java-1.7.0-openjdk

- name: Move Jboss to Install location
  copy: src=/vagrant/disconnected/jboss-as-7.1.1.Final.zip dest=/opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  command: chdir=/usr/share /usr/bin/unzip -q /opt/jboss-as-7.1.1.Final.zip creates=/usr/share/jboss-as

  # Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv jboss-as-7.1.1.Final jboss-as creates=/usr/share/jboss-as

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest=/usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  group: name=jboss

- name: Add user "jboss"
  user: name=jboss group=jboss home=/usr/share/jboss-as

- name: Change ownership of JBoss installation
  file: path=/usr/share/jboss-as/ owner=jboss group=jboss state=directory recurse=yes

- name: Copy the init script
  copy: src=jboss-as-standalone.sh dest=/etc/init.d/jboss mode=0755

- name: Install JBoss Applications
  shell: "cp -f /vagrant/jboss-apps/*.war /usr/share/jboss-as/standalone/deployments"

- name: Enable JBoss to be started at boot
  service: name=jboss enabled=yes state=started

- name: Discard iptables rules
  command: iptables -F

- meta: flush_handlers
